<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <!--            <a class="navbar-brand" href="#">-->
            <!--                <img alt="Brand" src="...">-->
            <!--            </a>-->
            <div class="nav navbar-left">
                <a class="navbar-brand">Form</a>
            </div>
            <form class="nav navbar-form navbar-right" method="post">
                <div class="form-group">
                    <button type="submit" class="btn btn-default" name="logoutbtn">Logout</button>
                </div>
            </form>
        </div>
    </div>
</nav>